[workspace]
resolver = "2"
members = [
    "app",
    "core",
    "ui"
]

[package]
name = "media-player-dev"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dev"
path = "dev.rs"

[dependencies]
notify = "5.0"
ctrlc = "3.2"