[package]
name = "media-player"
version = "0.1.0"
edition = "2021"
build = "scripts/build.rs"

[dependencies]
symphonia = { version = "0.5.3", features = ["all"] }
cpal = "0.15.2"
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
iced = "0.9"

[build-dependencies]
pkg-config = "0.3"
