[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_json = "1.0"
anyhow = "1.0"
cpal = "0.15.2"
log = "0.4"
iced = "0.13.1"
symphonia = { version = "0.5.3", features = ["mp3", "wav", "flac"] }
