[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.9", features = ["tokio"] }
hot-lib-reloader = "0.6"
core = { path = "../core" }
tokio = { version = "1", features = ["time", "rt", "macros"] }
log = "0.4"
env_logger = "0.10"
ctrlc = "3.2"