[env]
VCPKG_DEFAULT_TRIPLET = "x64-windows"
VCPKG_TRIPLET = "x64-windows"

[build]
incremental = true
# Comment out sccache until properly configured
# rustc-wrapper = "sccache"
target-dir = "target"
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-pc-windows-msvc]
linker = "lld-link"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "link-arg=/LTCG", "-C", "target-cpu=native"]

[profile.dev]
opt-level = 0
debug = false  # Set to false for faster compiles, true for better debugging
split-debuginfo = "unpacked"  # Helps with incremental builds
codegen-units = 256  # Maximum parallelism
lto = false
panic = "abort"  # Slightly faster builds

# Only use these if you're on nightly and have cranelift installed
# [unstable]
# build-std = ["std", "panic_abort"]