[env]
VCPKG_DEFAULT_TRIPLET = "x64-windows"
VCPKG_TRIPLET = "x64-windows"

[build]
incremental = true
rustc-wrapper = "sccache"
target-dir = "target"
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-pc-windows-msvc]
linker = "lld-link"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "link-arg=/LTCG", "-C", "target-cpu=native"]

[profile.dev]
opt-level = 0
debug = false
split-debuginfo = "unpacked"
codegen-units = 256
lto = false
panic = "abort"
