[env]
VCPKG_ROOT = "C:/vcpkg"
VCPKG_DEFAULT_TRIPLET = "x64-windows"
VCPKG_TRIPLET = "x64-windows"
RUST_BACKTRACE = "full"
FFMPEG_PKG_CONFIG_PATH = "C:/vcpkg/installed/x64-windows-static-md/lib/pkgconfig"
PKG_CONFIG_PATH = "C:/vcpkg/installed/x64-windows-static-md/lib/pkgconfig"

[build]
incremental = true
rustc-wrapper = "sccache"
target-dir = "target"
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=/NODEFAULTLIB:libcmt"]
[target.x86_64-pc-windows-msvc]
linker = "lld-link"
[profile.dev]
opt-level = 0
debug = false
split-debuginfo = "unpacked"
codegen-units = 256
lto = false
panic = "abort"
